### ISSUE TITLE
Team project first deliverables ready for review

### ISSUE THREAD

**Issue by jbjohnson2** [jbjohnson2/EntJavaTeamProject#1]
@pawaitemadisoncollege 
We have our team project start ready for review

**Comment by pawaitemadisoncollege** [comment]
Hi Team (@jbjohnson2 @Xeexuku @OscarJohnson6 @JBostroem96). You have a good start here with your repo, problem statement, charter, plan, and related documents.  Looks like you already have a good start with code too - with a dao that is unit tested. Well done! 

A few things:

- [x] Scope - can you share what resources, which operations (get, put, post, delete) on which resources you will support, and the response types you'll support (json, xml, plain text, html, etc). This will help me understand the scope and give me the opportunity to provide some guidance on the project size. 

- [x] Team charter - consider adding something about how you will handle a situation where a team member becomes unresponsive? I know we hope these things don't happen, but it's still good to discuss it and have a plan.  Consider some guidelines around how you will use git/github. Branching? Pull requests? 

- [x] A couple bad "links" at the bottom of this page: https://github.com/jbjohnson2/EntJavaTeamProject/blob/main/readme.md

- [x] Consider also appealing to the developer of an application in your problem statement - the main "customer" of your web service is a developer building an application that will consume your service. That's not to say a "regular" person couldn't access your service through your user guide to get at the data. (I realize I should have done a better job modeling this in the demo repo).

**Comment by jbjohnson2** [comment]
@pawaitemadisoncollege 
Scope - we plan to return JSON and possibly HTML.
operations -  Get  all festivals, get all regions, get all types, get festival by id, get festival by region, get festival by type, get region by id, get type by id and post festival.
Team charter is updated
Links are fixed 
Problem statement  updated

**Comment by pawaitemadisoncollege** [comment]
Hi Team - thanks for the updates and good job with the improvements/clarifications. 

I think your scope is well-sized based the resources/operations/response types that you shared.  Once complete, that information would be good to put on the readme.md so anyone viewing the repo can easily see what is supported OR include a link in the readme.md that goes your user guide.
